export enum ActionType {
    GET_ALL_DATA_ANALYSIS = 'GET_ALL_DATA_ANALYSIS',
    GET_ALL_COUNTRIES = 'GET_ALL_COUNTRIES',
    GET_ALL_CAMPS = 'GET_ALL_CAMPS',
    GET_ALL_SCHOOLS = 'GET_ALL_SCHOOLS',
    FILTER_STATE = 'FILTER_STATE',
    FILTERED_LESSONS_BY_CAMP = 'FILTERED_LESSONS_BY_CAMP',
    CHART_SELECTED_SCHOOLS = 'CHART_SELECTED_SCHOOLS'
    
  }