export enum ActionType {
  GET_ALL_DATA_ANALYSIS = 'GET_ALL_DATA_ANALYSIS',
  GET_ALL_COUNTRIES = 'GET_ALL_COUNTRIES',
  GET_ALL_CAMPS = 'GET_ALL_CAMPS',
  FILTER_STATE = 'FILTER_STATE',
  FILTERED_LESSONS_BY_CAMP = 'FILTERED_LESSONS_BY_CAMP',
  CHART_SELECTED_SCHOOLS = 'CHART_SELECTED_SCHOOLS',
  SELECTED_SCHOOLS_RELATED_TO_COUNTRY_AND_CAMP = 'SELECTED_SCHOOLS_RELATED_TO_COUNTRY_AND_CAMP'
}
